import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f7f9fb",
        "on-primary-fixed": "#002113",
        "tertiary": "#006c49",
        "surface-container": "#eceef0",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-tint": "#006c49",
        "outline": "#6c7b71",
        "primary": "#006c49",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#34e09f",
        "outline-variant": "#bacabf",
        "surface-container-high": "#e6e8ea",
        "on-primary-container": "#005135",
        "on-primary": "#ffffff",
        "tertiary-container": "#39cb91",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#cdd9ff",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#34e09f",
        "primary-fixed": "#5cfdba",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary": "#515e7e",
        "on-surface-variant": "#3c4a41",
        "primary-container": "#00cd8e",
        "on-error": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
